spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amayadream/config-repo/       # 配置git仓库的地址
          search-paths:                                         # git仓库地址下的相对地址, 多个用英文逗号分隔
          username:                                             # git仓库的账号
          password:                                             # git仓库的密码

server:
  port: 8700

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8600/eureka/